pipeline:
    build:
        image: python:3.7-slim
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
        commands:
            - pip install pipenv && pipenv install --system
            - python ./manage.py test
        when:
            branch: [ master ]
            event: [push, pull_request]

    publish:
        image: plugins/docker
        repo: pwbryant/drone-proj
        tags: latest
        secrets: [docker_username, docker_password]
        environment:
            - DOCKER_LAUNCH_DEBUG=true
        when:
            branch: [ master ]
            event: [ push ]

    ssh-deploy:
        image: appleboy/drone-ssh
        pull: true  # always pull the latest version of the `drone-ssh` plugin
        host: 
            from_secret: stage_host
        # ec2-3-15-204-120.us-east-2.compute.amazonaws.com  # passed in as a drone secret
        username: ${USER} # passed in as a drone secret
        volumes:
            - /home/ubuntu/.ssh/drone-key-pair.pem:/home/ubuntu/.ssh/drone-key-pair.pem
        key_path: /home/ubuntu/.ssh/drone-key-pair.pem
        port: 22
        pull: true
        command_timeout: 2m
        script:
            - cd /home/ubuntu  # or whereever you put your `deploy.sh`
            - sh deploy.sh
        when:
            event: [push, tag, deployment]

services:
    db:
        image: postgres
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
