pipeline:
    build:
        image: python:3.7-slim
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
        commands:
            - pip install pipenv && pipenv install --system
            - python ./manage.py test
        when:
            branch: [ master ]
            #event: [push, pull_request]
services:
    db:
        image: postgres
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
