pipeline:
    build:
        image: python:3.7-slim
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
        commands:
            - pip install pipenv && pipenv install --system
            - python ./manage.py test
        when:
            branch: [ master ]
            event: [push, pull_request]

    publish:
        image: plugins/docker
        settings:
            username: ${DOCKER_USERNAME}
            password: ${DOCKER_PASSWORD}
            email: paulwilliambryant@gmail.com
            repo: pwbryant/drone-proj
            registry: registry.hub.docker.com
            tags: [ "latest" ]
        environment:
            - DOCKER_LAUNCH_DEBUG=true
        when:
            branch: [ master ]
            event: [ push ]

services:
    db:
        image: postgres
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
