pipeline:
    build:
        name: web
        image: python:3.7-slim
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
        commands:
            - pip install pipenv && pipenv install --system
            - pytest hello
        when:
            branch: [ master ]
            event: [push, pull_request]

    publish:
        image: plugins/docker
        repo: pwbryant/drone-proj
        tags: latest
        secrets: [docker_username, docker_password]
        environment:
            - DOCKER_LAUNCH_DEBUG=true
        when:
            branch: [ master ]
            event: [ push ]

services:
    db:
        image: postgres
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
        ports:
            - 5432:5432
