version: '3.3'

services:
    web:
        build: .
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
        command: gunicorn drone_project.wsgi -b 0.0.0.0:8000
        volumes:
            - .:/code/
        ports:
            - 8000:8000
        depends_on:
            - db
            - hub

    db:
        image: postgres
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres

    hub:
        image: selenium/hub:3.141.59
        ports:
            - 4444:4444

    chrome:
        image: selenium/node-chrome:3.141.59
        environment:
            - HUB_HOST=hub
        depends_on:
            - hub

    firefox:
        image: selenium/node-firefox:3.141.59
        environment:
            - HUB_HOST=hub
        depends_on:
            - hub
