version: '3.3'

services:
    web:
        build: .
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code/
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
